tasks:
  - name: arc-package
    actions:
      - description: Create the ARC Zarf package
        cmd: uds zarf package create --set VERSION=0.1.0 --confirm --no-progress

  - name: arc-bundle
    actions:
      - description: Create the ARC UDS bundle
        cmd: uds create examples/uds-self-hosted-runner/ --confirm --no-progress
